--- Find the Total Sales
SELECT SUM(sales_amount) AS total_sales FROM dbo.[gold.fact_sales]

--- Find how many items are sold
SELECT COUNT(quantity) AS total_items_sold FROM dbo.[gold.fact_sales]

--- Find the average selling price 
SELECT AVG(sales_amount) AS total_items_sold FROM dbo.[gold.fact_sales]

--- Find the Total number of Orders
SELECT COUNT(order_number) AS total_orders FROM dbo.[gold.fact_sales] --- repeated and non repeated customers
SELECT COUNT(DISTINCT order_number) AS total_orders_unique FROM dbo.[gold.fact_sales] --- unqiue customers atleast orderd one time 

--- Find the Total number of products 
SELECT COUNT(product_key) AS total_products FROM dbo.[gold.dim_products]
SELECT COUNT(DISTINCT product_key) AS total_products FROM dbo.[gold.dim_products]

--- Find the total number of customers
SELECT COUNT(customer_id) AS total_customers FROM dbo.[gold.dim_customers]

--- Find the total number of customers that has placed and order
SELECT COUNT(customer_key) AS total_customers_placed_orders FROM dbo.[gold.fact_sales]

---Generate report that show all matrices of the business
SELECT 'total_sales' AS measure_name, SUM(sales_amount) AS measure_value  FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'total_items_sold' AS measure_name, COUNT(quantity) AS measure_value FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'total_items_sold' AS measure_name, AVG(sales_amount) AS measure_value FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'total_orders' AS measure_name, COUNT(order_number) AS measure_value FROM dbo.[gold.fact_sales]
UNION ALL
SELECT 'total_products' AS measure_name, COUNT(product_key) AS measure_value FROM dbo.[gold.dim_products]
UNION ALL
SELECT 'total_customers' AS measure_name, COUNT(customer_id) AS measure_value  FROM dbo.[gold.dim_customers]
UNION ALL
SELECT 'total_customers_placed_orders' AS measure_name, COUNT(customer_key) AS measure_value FROM dbo.[gold.fact_sales]





--- Find total number of customers by countries
SELECT 
country,
COUNT(customer_id) AS total_customers 
FROM dbo.[gold.dim_customers]
GROUP BY country
ORDER BY COUNT(customer_id) DESC

---Find total customer by gender 
SELECT 
gender,
COUNT(customer_id) AS total_customersASPERgender
FROM dbo.[gold.dim_customers]
GROUP BY gender
ORDER BY COUNT(customer_id) DESC

---Find total products by category 
SELECT 
category,
COUNT(product_number) AS total_productsPERcategory 
FROM dbo.[gold.dim_products]
GROUP BY category
ORDER BY COUNT(product_number) DESC

---What is the average costs in each category?
SELECT 
category,
AVG(cost) AS AvergeCostPer_category
FROM dbo.[gold.dim_products]
GROUP BY category
ORDER BY AVG(cost) DESC

---What is the total revenue generated for each category? 
SELECT 
st.category,
SUM(ft.sales_amount) AS AvergeCostPer_category
FROM dbo.[gold.fact_sales] AS ft
LEFT JOIN dbo.[gold.dim_products] AS st
ON ft.product_key = st.product_key
GROUP BY st.category
ORDER BY SUM(ft.sales_amount) DESC

---Find total revenue is generated by each customer 
SELECT 
st.customer_key,
SUM(dt.sales_amount) AS total_revenue
FROM dbo.[gold.dim_customers] AS st
LEFT JOIN dbo.[gold.fact_sales] AS dt
ON st.customer_key = dt.customer_key
GROUP BY st.customer_key
ORDER BY SUM(dt.sales_amount) DESC

---What is the distribution of sold items across countries? 
SELECT 
tn.country, 
SUM(tm.quantity) AS total_sold_items
FROM dbo.[gold.dim_customers] AS tn
LEFT JOIN dbo.[gold.fact_sales] AS tm
ON tn.customer_key = tm.customer_key
GROUP BY tn.country
ORDER BY SUM(tm.quantity) DESC


SELECT * FROM dbo.[gold.dim_customers]
SELECT * FROM dbo.[gold.dim_products]
SELECT * FROM dbo.[gold.fact_sales]






--- Explore ALL Countries our customers come from
SELECT DISTINCT country
FROM dbo.[gold.dim_customers];

--- Explore All Categories 'The major Divisions'
SELECT DISTINCT category, subcategory,product_name FROM dbo.[gold.dim_products]
ORDER BY 1,2,3

--- Find the Date of the first and last order
SELECT MIN(order_date) AS first_order_order,
MAX(order_date) AS last_order_order,
DATEDIFF(MONTH,MIN(order_date),MAX(order_date)) AS order_range_months
FROM dbo.[gold.fact_sales]

--- Find the Youngest and oldest customer
SELECT MIN(birthdate) AS oldest_customer,
DATEDIFF(YEAR,MIN(birthdate), GETDATE()) AS oldest_age,
MAX(birthdate) AS youngest_customers,
DATEDIFF(YEAR,MAX(birthdate), GETDATE()) AS yongest_age
FROM dbo.[gold.dim_customers]




---Which 5 products generate the highest revenu

SELECT*

FROM(
SELECT  
ds.product_name, 
SUM(sd.sales_amount) AS total_revenueByProducts,
ROW_NUMBER() OVER(ORDER BY SUM(sd.sales_amount) DESC) AS RANK_
FROM  dbo.[gold.fact_sales] AS sd
LEFT JOIN dbo.[gold.dim_products] AS ds
ON ds.product_key = sd.product_key
GROUP BY ds.product_name
)t
WHERE RANK_ <= 5

--- What are 5 wrost_performing products in terms of sales?
SELECT*

FROM(
SELECT 
ds.product_name, 
SUM(sd.sales_amount) AS total_revenueByProducts,
ROW_NUMBER() OVER(ORDER BY SUM(sd.sales_amount) ) AS RANK_
FROM  dbo.[gold.fact_sales] AS sd
LEFT JOIN dbo.[gold.dim_products] AS ds
ON ds.product_key = sd.product_key
GROUP BY ds.product_name
)t
WHERE RANK_ <= 5


--- or 
SELECT TOP 5
ds.product_name, 
SUM(sd.sales_amount) AS total_revenueByProducts
FROM  dbo.[gold.fact_sales] AS sd
LEFT JOIN dbo.[gold.dim_products] AS ds
ON ds.product_key = sd.product_key
GROUP BY ds.product_name
ORDER BY SUM(sd.sales_amount) DESC

SELECT TOP 5
ds.product_name, 
SUM(sd.sales_amount) AS total_revenueByProducts
FROM  dbo.[gold.fact_sales] AS sd
LEFT JOIN dbo.[gold.dim_products] AS ds
ON ds.product_key = sd.product_key
GROUP BY ds.product_name
ORDER BY SUM(sd.sales_amount) 



